### ISSUE TITLE
[Yatse] update url for playing a video

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#176]
```python
plugin://plugin.video.youtube/play/?video_id=[VID]
```

**Comment by Tolriq** [comment]
Just found this by luck after having an user opening a case for changed endpoint for vimeo.

@bromix can you confirm all those new endpoints work on current plugin version in XBMC / Kodi official repository and support all from Frodo ?

**Comment by bromix** [comment]
The new addons are only available starting with Helix (14.0) - so starting with Helix you will only have the new End-Points. I give no support for versions before.
Frodo is discontinued.

**Comment by Tolriq** [comment]
Well youtube old endpoints still works I suppose for Kodi as I would have received thousands of mail if it was not :(

Is there a reason for deprecation ? Will they stay stable ?

**Comment by bromix** [comment]
For now I support the old End-Points but I'm planing on removing them with Isengard - you already see a deprecation warning in the logs since December 2014.

The reason for that is - old URIs are a pain and someone didn't know how to use them correctly. URIs can resemble clean hierarchies without polluting the query with parameter. The new End-Points (in my opinion) are much cleaner to read and mostly self explaining and are orientated on existing REST-APIs

One other reason was, with new End-Points (URIs) KODI can finally track watched videos correctly. The old addon produced unneeded problems if you were using playlists or the 'Watch Later' list, because of additional parameters in the query.

**Comment by Tolriq** [comment]
Well I do not really use all the plugins I support :)
Most of the time plugins author contact me so I add support for their plugin.

I guess it's time for me to go find someone that knows python to build the missing piece for addons somekind or urlresolver but for addons.

That would serve many remotes and tools out there and it's way easier to push addons to Kodi than update of remotes.

Maybe you are interested or know someone who would be ? :)

**Comment by bromix** [comment]
If I understand you correct :) you mean an Addon which will get all the calls from YaTse, but will relay/call the correct addon afterwords on the users machine.

Like SoundCloud, you're already sending the complete URL (but directly to the SoundCloud addon). 

Some kind of Yatse addon or more common? I love the idea if I understand you correct, because the user could make adjustments and we could use the original url (www.youtube.com/watch?v=XXXXX)

**Comment by Tolriq** [comment]
Yes a plugin resolver but global not only for Yatse, it would be for Yatse only, only if no one can help me and I take multiple days to learn Python and all those things so would have to push more toward my users as a + for the start.

The goal is multiple : 
- Allow simpler plugin resolution as it's hard to maintain for all remote makers and easier to push update, I can't push a new Yatse release to million users just because a new plugin is out or an endpoint change that 0.01% users use.
- Allow user configuration for case where multiple plugins can handle the link (for example all torrent plugins that support magnet links).

I see it like a simple : plugin://plugin.resolver/resolve/?url=XXXX 

And maybe with a fallback to url resolver if no plugin available to handle (but not sure exactly if url resolver can extract directly usable streams for Kodi.

**Comment by bromix** [comment]
@Tolriq I close this issue, because the basic discussion of that is in the KODI forum and I will try to keep it up there...but this Issue was basically a reminder.
