### ISSUE TITLE
Why you always removes previous tags and releases?

### ISSUE THREAD

**Issue by Dukobpa3** [bromix/plugin.video.youtube#250]
Subj.
I think you miss your history because of it.

**Comment by bromix** [comment]
No...I live in the future ;) what is the benefit of it :)

**Comment by Dukobpa3** [comment]
Backward compatibility?))
For now I can't to set up prev version on older kodi etc.
It is just a tag. Which reason to delete it?

**Comment by bromix** [comment]
Backward compatibility for what :) please explain the problem - YouTube is even running on Gotham. The KODION framework is doing the lifting.

**Comment by Dukobpa3** [comment]
I'm a developer :)
I break the pattern of such approaches :D

**Comment by bromix** [comment]
Great answer, me too + product management...and now ;)
You haven't really specified the problem. If something isn't running file an issue, fork the current release/tag 5.1.0. The version before (5.0.9 won't run flawless, because of the deprecation of APIv2 (so the old stuff isn't doing so good for me ;) ).

**Comment by Dukobpa3** [comment]
Maybe you are right.
But I can't see the reason for deletion tags.

**Comment by bromix** [comment]
The 5.1.0 is the first (I think) release/tag I created. More releases/tags will follow ;) you're right also :)
